/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Add type declaration for react-native-qrcode-styled
declare module 'react-native-qrcode-styled' {
  import { ComponentType } from 'react'
  import { ImageSourcePropType, ViewStyle } from 'react-native'

  interface QRCodeStyledProps {
    data: string
    style?: ViewStyle
    pieceSize?: number
    pieceBorderRadius?: number
    isPiecesGlued?: boolean
    color?: string
    backgroundColor?: string
    innerEyesOptions?: {
      borderRadius?: number
      color?: string
    }
    outerEyesOptions?: {
      borderRadius?: number
      color?: string
    }
    logo?: {
      href?: ImageSourcePropType
      padding?: number
      hidePieces?: boolean
    }
  }

  const QRCodeStyled: ComponentType<QRCodeStyledProps>
  export default QRCodeStyled
}
